apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-data-json
  name: spring-boot-data-json-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-data-json
  sessionAffinity: None
  type: ClusterIP

